[versions]
kotlin = "2.0.21"
ksp = "2.0.21-1.0.28"
coroutines = "1.9.0"
asm = "9.7.1"
kotlinpoet = "1.18.1"
dokka = "1.9.20"
binary-compatibility-validator = "0.16.3"
jmh-plugin = "0.7.2"
guava = "33.3.1-jre"
deamsy-eventbus = "1.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
deamsy-eventbus = { module = "com.github.deamsy:eventbus", version.ref = "deamsy-eventbus" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh-plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
