package dev.deftu.evocation.invokers

/**
 * Turns generated bytecode into a loaded class.
 *
 * The default rolls a child of the listener's own classloader, which is right
 * for an ordinary application and wrong wherever something else already owns
 * class loading. Mod loaders, application servers and plugin hosts all run their
 * own, and their author knows the arrangement better than this library can
 * guess, so they can supply one:
 *
 * ```kotlin
 * ClassDefiners.default = ClassDefiner { name, bytes -> myLoader.define(name, bytes) }
 * ```
 *
 * Returning null, or throwing, declines generation for that event type and the
 * bus falls back to interpreted dispatch.
 */
public fun interface ClassDefiner {
    public fun define(name: String, bytes: ByteArray, neighbour: Class<*>): Class<*>?
}

public object ClassDefiners {
    /**
     * Defines into a fresh child of the neighbour's loader.
     *
     * One loader per generated class, so a class becomes collectable as soon as
     * the dispatcher holding it does. A shared loader would accumulate them for
     * the life of the process.
     */
    public val childLoader: ClassDefiner = ClassDefiner { name, bytes, neighbour ->
        val parent = neighbour.classLoader ?: ClassLoader.getSystemClassLoader() ?: return@ClassDefiner null
        GeneratedClassLoader(parent).define(name, bytes)
    }

    /** Used when nothing else is configured. Assign to override globally. */
    @JvmStatic
    public var default: ClassDefiner = childLoader

    private class GeneratedClassLoader(parent: ClassLoader) : ClassLoader(parent) {
        fun define(name: String, bytes: ByteArray): Class<*> = defineClass(name, bytes, 0, bytes.size)
    }
}
